### ISSUE TITLE
I get an error when visiting my bookmark

### ISSUE THREAD

**Issue by joelhellman** [RasmusRossetti/TimeLockBeta#1]
I have bookmarked timelocker.se/account, but when I visit the site, I get a error that page does not exist. 

Can this be fixed?

**Comment by RasmusRossetti** [comment]
Dear Joel,

I wanted to let you know that we have resolved the issue you reported about not being able to access the timelocke.se/account page.

We were able to identify the problem and implement a fix to ensure that the page is now accessible and working properly. We apologize for any inconvenience this may have caused and we appreciate your patience while we resolved this issue.

Thank you for bringing this to our attention and for your continued use of TimeLock. If you have any further questions or concerns, please don't hesitate to reach out to us.

Best regards,

The Team

**Comment by joelhellman** [comment]
It seems to work now. Thanks Team :)
