### ISSUE TITLE
Remember me? 

### ISSUE THREAD

**Issue by joelhellman** [RasmusRossetti/TimeLockBeta#3]
I often use a lot of tabs, but when I close down TimeLock, I have to login again. 
I'd like the site to remember me if I have logged in, so I don't have to re-login every time. 

Altough maybe at some point, I should need to login again.

**Comment by RasmusRossetti** [comment]
Hi Joel, 
TimeLock now remembers users who have logged in. This is achieved using local storage, so when you visit timelock.se/account, you will be redirected to your account without having to log in again. However, it's important to note that for security reasons, users may still need to log in again at some point in the future.

Best 
The Team

**Comment by joelhellman** [comment]
Thanks, it works.
