### ISSUE TITLE
My neighbord hogs the wash the entire day

### ISSUE THREAD

**Issue by joelhellman** [RasmusRossetti/TimeLockBeta#5]
My neighbor is crazy. He always book two time slots at once. 

I want a rule so you cannot book too many times. 

Absolutely not book twice on the same day. 

Also, it would be nice if everybody could have at most one booking per week.

**Comment by RasmusRossetti** [comment]
Hi Joel,

Thank you for your suggestion. We have already implemented a rule that limits users to booking only one timeslot per day. This ensures that users cannot book two time slots on the same day

We appreciate your feedback and hope that these rules help to create a fair and equitable booking system for all users.

Best regards,
The Team

**Comment by joelhellman** [comment]
That solves my issue. Thanks.
